services:
  pascal-db:
    image: postgres:16
    volumes:
      - pascal-data:/var/lib/postgresql/data
    environment:
      - TZ=America/Lima
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=PASCAL
    ports:
      - 5432:5432

volumes:
  pascal-data:
